/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.misiontic2022.c2.cdiaz.vista;

import co.edu.utp.misiontic2022.c2.cdiaz.controlador.HumanResourcesController;
import co.edu.utp.misiontic2022.c2.cdiaz.modelo.vo.Department;
import co.edu.utp.misiontic2022.c2.cdiaz.modelo.vo.Employee;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ROG
 */
public class FrmRecursosHumanos extends javax.swing.JFrame {

    private HumanResourcesController controller;
    private EmpleadosTableModel empleadosTableModel;

    /**
     * Creates new form FrmRecursosHumanos
     */
    public FrmRecursosHumanos() {
        controller = new HumanResourcesController();

        initComponents();
        cargarInfoInicial();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdVentanas = new javax.swing.JTabbedPane();
        pnlEmpleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNuevoEmpleado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        btnGuardarEmpleado = new javax.swing.JButton();
        pnlDepartamentos = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miDepartamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion de Recursos Humanos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlEmpleados.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Empleados");
        pnlEmpleados.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(300);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnNuevoEmpleado.setText("Nuevo");
        btnNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevoEmpleado);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel3.add(jSeparator1);

        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setEnabled(false);
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarEmpleado);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel2.setText("ID");

        txtId.setEditable(false);

        jLabel3.setText("Nombre");

        jLabel4.setText("Correo electrónico");

        jLabel5.setText("Departamento");

        btnGuardarEmpleado.setText("Guardar");
        btnGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreoElectronico))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDepartamento, 0, 188, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarEmpleado)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarEmpleado)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        pnlEmpleados.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tbdVentanas.addTab("Empleados", pnlEmpleados);

        javax.swing.GroupLayout pnlDepartamentosLayout = new javax.swing.GroupLayout(pnlDepartamentos);
        pnlDepartamentos.setLayout(pnlDepartamentosLayout);
        pnlDepartamentosLayout.setHorizontalGroup(
            pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        pnlDepartamentosLayout.setVerticalGroup(
            pnlDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        tbdVentanas.addTab("Departamentos", pnlDepartamentos);

        getContentPane().add(tbdVentanas, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        miSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventanas");

        miEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miEmpleados.setText("Empleados");
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(miEmpleados);

        miDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miDepartamentos.setText("Departamentos");
        miDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDepartamentosActionPerformed(evt);
            }
        });
        jMenu2.add(miDepartamentos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        cerrarAplicacion();
    }//GEN-LAST:event_miSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarAplicacion();
    }//GEN-LAST:event_formWindowClosing

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed
        tbdVentanas.setSelectedIndex(0);
    }//GEN-LAST:event_miEmpleadosActionPerformed

    private void miDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDepartamentosActionPerformed
        tbdVentanas.setSelectedIndex(1);
    }//GEN-LAST:event_miDepartamentosActionPerformed

    private void btnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoActionPerformed
        nuevoEmpleado();
    }//GEN-LAST:event_btnNuevoEmpleadoActionPerformed

    private void btnGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleadoActionPerformed
        guardarEmpleado();
    }//GEN-LAST:event_btnGuardarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        eliminarEmpleado();
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void cerrarAplicacion() throws HeadlessException {
        if (JOptionPane.showConfirmDialog(this, "Está seguro en salir?", getTitle(), JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    private void cargarInfoInicial() {
        try {
            // Cargar listado de empleados
            var employees = controller.findAllEmployees();
            empleadosTableModel = new EmpleadosTableModel(employees);
            tblEmpleados.setModel(empleadosTableModel);

            tblEmpleados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblEmpleados.getSelectionModel().addListSelectionListener((e) -> {
                var row = tblEmpleados.getSelectedRow();
                if (row == -1) { // No hay filas seleccionadas
                    limpiarCampos();
                    btnEliminarEmpleado.setEnabled(false);
                } else {
                    var employee = empleadosTableModel.getEmployee(row);
                    cargarDatosEmpleado(employee);
                    btnEliminarEmpleado.setEnabled(true);
                }
            });

            // Listado de departamentos
            var departamentos = controller.findAllDepartments();
            cmbDepartamento.removeAllItems();
            departamentos.forEach(departamento -> {
                cmbDepartamento.addItem(departamento);
            });
            cmbDepartamento.setSelectedIndex(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        tblEmpleados.clearSelection();

        txtId.setText("");
        txtNombre.setText("");
        txtCorreoElectronico.setText("");
        cmbDepartamento.setSelectedIndex(-1);
    }

    private void nuevoEmpleado() {
        limpiarCampos();

        txtNombre.requestFocus();
    }

    private void cargarDatosEmpleado(Employee employee) {
        txtId.setText(employee.getId().toString());
        txtNombre.setText(employee.getName());
        txtCorreoElectronico.setText(employee.getEmail());
        cmbDepartamento.setSelectedItem(employee.getDepartment());
    }

    private void guardarEmpleado() {
        // Validar datos obligatorios
        if (txtNombre.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El campo nombre es obligatorio");
            txtNombre.requestFocus();
            return;
        }
        if (cmbDepartamento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "El campo departamento es obligatorio");
            cmbDepartamento.requestFocus();
            return;
        }

        // Obtengo la informacion de pantalla
        var id = txtId.getText().trim();
        var nombre = txtNombre.getText().trim();
        var email = txtCorreoElectronico.getText().trim();
        var departamento = (Department) cmbDepartamento.getSelectedItem();

        // Envio a guardar a la base de datos
        try {
            if (id.isBlank()) {
                var employee = controller.createEmployee(nombre, email, departamento.getId());
                // Agregarlo a la tabla de empleados
                empleadosTableModel.addEmployee(employee);
            } else {
                var row = tblEmpleados.getSelectedRow();
                var employee = controller.updateEmployee(Integer.valueOf(id), nombre, email, departamento.getId());
                // Actualizar el renglon de la tabla empleados
                empleadosTableModel.setEmployee(row, employee);
            }

            // Confirmar guardado
            JOptionPane.showMessageDialog(this, "El empleado ha sido guardado exitosamente");
            limpiarCampos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminarEmpleado() {
        if (JOptionPane.showConfirmDialog(this, "Está seguro en eliminar este empleado?",
                getTitle(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // Obtengo el id el empleado
            var id = Integer.valueOf(txtId.getText());
            try {
                controller.deleteEmployee(id);
                empleadosTableModel.removeEmployee(tblEmpleados.getSelectedRow());
                JOptionPane.showMessageDialog(this, "El empleado ha sido eliminado exitosamente");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecursosHumanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnGuardarEmpleado;
    private javax.swing.JButton btnNuevoEmpleado;
    private javax.swing.JComboBox<Department> cmbDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem miDepartamentos;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JPanel pnlDepartamentos;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JTabbedPane tbdVentanas;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
